#!/usr/bin/php
<?php

if (php_sapi_name() !== 'cli') {
    exit;
}

require __DIR__ . '/vendor/autoload.php';

use Config\Config;
use src\App;
use src\Database\Mysql\Mysql;

$app = null;
$db = null;
try {
    $app = new App($argv);
    $db = new Mysql(Config::$host, Config::$name, Config::$user, Config::$password);
    // $app->testSearchInDatabase($db);
    $app->printList($app->searchInDatabase($db));
} catch (Exception $e) {
    echo "{$e->getMessage()}";
}
